moved quorum send

diff --git a/.github/workflows/train.yml b/.github/workflows/train.yml
--- a/.github/workflows/train.yml
+++ b/.github/workflows/train.yml
@@ -22,6 +22,20 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
+      # - name: check directories
+      #   run: |
+      #     cd src
+      #     DIR="../../../../../../../home"
+      #     if [ -d "$DIR" ]; then
+      #       ### Take action if $DIR exists ###
+      #       echo "Installing config files in ${DIR}"
+      #       exit 1
+      #     else
+      #       ###  Control will jump here if $DIR does NOT exists ###
+      #       echo "Error: ${DIR} not found. Can not continue."
+      #       exit 1
+      #     fi
+
       # Step 2: Set up Python
       - name: Set up Python
         uses: actions/setup-python@v4
@@ -49,8 +63,12 @@ jobs:
           python main.py -super true -s "./configs/sys_config_test.py"
           echo "done"
 
-      # further checks:
-      # only 5 rounds
-      # gRPC only? or also MPI?
-      # num of samples
-      # num users and nodes
+      - name: Clean up
+        run: |
+          rm -rf ./sonar_experiments/  
+
+          # further checks:
+            # only 5 rounds
+            # gRPC only? or also MPI?
+            # num of samples
+            # num users and nodes
